import type { Task, BudgetExpense, FundSource, GalleryImage } from './types';

export const initialTasks: Task[] = [
  // === 계약/행정 ===
  {
    id: 'contract-1',
    category: 'contract',
    title: '약정서 작성 - 매도인에게 약정금 전달',
    description: '약정금 4,000만원 매도인에게 전달',
    deadline: '2026-07-04',
    completed: true,
    estimatedCost: 4000,
    actualCost: 4000,
    relatedImages: ['/buying_home_project/contract/매매 약정서.jpeg'],
  },
  {
    id: 'contract-2',
    category: 'contract',
    title: '토허제 거래 신고 (법무사 대행)',
    description: '법무사 대행료 20만원 입금',
    deadline: '2026-07-06',
    completed: true,
    estimatedCost: 20,
    actualCost: 20,
    relatedImages: [
      '/buying_home_project/contract/토허제-1.jpeg',
      '/buying_home_project/contract/토허제-2.jpeg',
      '/buying_home_project/contract/토허제-3.jpeg',
      '/buying_home_project/contract/토허제-4.png',
    ],
  },
  {
    id: 'contract-3',
    category: 'contract',
    title: '토허제 허가 발급',
    deadline: '2026-07-16',
    completed: true,
  },
  {
    id: 'contract-4',
    category: 'contract',
    title: '계약서 작성 - 계약금 납부',
    description: '계약금 9,000만원 (약정금 4,000만원 제외 5,000만원 추가 납부)',
    deadline: '2026-07-25',
    completed: false,
    estimatedCost: 5000,
  },
  {
    id: 'contract-5',
    category: 'contract',
    title: '매매 집 실측',
    description: '인테리어를 위한 실측 진행',
    deadline: '2026-07-28',
    completed: false,
  },
  {
    id: 'contract-6',
    category: 'contract',
    title: '중도금 납부',
    description: '중도금 2억 6,000만원 납부',
    deadline: '2026-09-28',
    completed: false,
    estimatedCost: 26000,
  },
  {
    id: 'contract-7',
    category: 'contract',
    title: '잔금 납부',
    description: '잔금 5억 8,000만원 납부',
    deadline: '2026-10-27',
    completed: false,
    estimatedCost: 58000,
  },
  {
    id: 'contract-8',
    category: 'contract',
    title: '소유권 이전 등기',
    description: '잔금 납부와 동시에 소유권 이전 등기 진행',
    deadline: '2026-10-27',
    completed: false,
  },
  {
    id: 'contract-9',
    category: 'contract',
    title: '전입신고',
    description: '입주 후 14일 이내 전입신고',
    deadline: '2026-10-28',
    completed: false,
  },

  // === 금융/대출 ===
  {
    id: 'finance-1',
    category: 'finance',
    title: '대출 가능 금액 확인',
    description: '은행 방문 또는 온라인으로 대출 한도 조회',
    deadline: '2026-07-25',
    completed: false,
  },
  {
    id: 'finance-2',
    category: 'finance',
    title: '대출 필요 서류 준비',
    description: '소득증명원, 재직증명서, 등기부등본, 매매계약서 등',
    deadline: '2026-08-15',
    completed: false,
  },
  {
    id: 'finance-3',
    category: 'finance',
    title: '대출 상담 및 신청',
    description: '은행 대출 상담 후 주담대 신청',
    deadline: '2026-09-01',
    completed: false,
  },
  {
    id: 'finance-4',
    category: 'finance',
    title: '대출 승인 확인',
    description: '대출 승인 여부 및 실행일 확인 (잔금일 전 완료 필수)',
    deadline: '2026-09-20',
    completed: false,
  },

  // === 세금/비용 ===
  {
    id: 'tax-1',
    category: 'tax',
    title: '취득세 납부',
    description: '잔금 납부일 기준 60일 이내 납부. 약 2,790만원 예상',
    deadline: '2026-10-30',
    completed: false,
    estimatedCost: 2790,
  },
  {
    id: 'tax-2',
    category: 'tax',
    title: '중개수수료(복비) 납부',
    description: '부동산 중개수수료 납부',
    deadline: '2026-10-27',
    completed: false,
    estimatedCost: 600,
  },

  // === 인테리어 ===
  {
    id: 'interior-1',
    category: 'interior',
    title: '인테리어 레퍼런스 수집',
    description: '원하는 스타일, 사진, 참고 자료 모으기',
    deadline: '2026-07-31',
    completed: false,
  },
  {
    id: 'interior-2',
    category: 'interior',
    title: '인테리어 업체 리서치 및 견적 요청',
    description: '3곳 이상 업체에 견적 요청',
    deadline: '2026-08-10',
    completed: false,
  },
  {
    id: 'interior-3',
    category: 'interior',
    title: '인테리어 업체 미팅',
    description: '업체별 미팅 및 견적 비교',
    deadline: '2026-08-20',
    completed: false,
  },
  {
    id: 'interior-4',
    category: 'interior',
    title: '인테리어 업체 선정 및 계약',
    description: '최종 업체 선정 후 계약 진행',
    deadline: '2026-08-31',
    completed: false,
    estimatedCost: 5000,
  },
  {
    id: 'interior-5',
    category: 'interior',
    title: '인테리어 공사 진행 상황 확인',
    description: '정기적으로 현장 방문 및 진행 상황 체크',
    deadline: '2026-09-15',
    completed: false,
  },
  {
    id: 'interior-6',
    category: 'interior',
    title: '인테리어 공사 완료 확인 / 하자 체크',
    description: '최종 시공 확인 및 하자 점검',
    deadline: '2026-10-20',
    completed: false,
  },

  // === 가전 구입 ===
  {
    id: 'appliance-1',
    category: 'appliance',
    title: '냉장고 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-2',
    category: 'appliance',
    title: '식기세척기 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-3',
    category: 'appliance',
    title: '인덕션 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-4',
    category: 'appliance',
    title: '세탁기 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-5',
    category: 'appliance',
    title: '건조기 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-6',
    category: 'appliance',
    title: '에어컨 2in1 (스탠드) 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-7',
    category: 'appliance',
    title: '에어컨 벽걸이 구입',
    deadline: '2026-10-01',
    completed: false,
  },
  {
    id: 'appliance-8',
    category: 'appliance',
    title: '가전 배송일 조율',
    description: '인테리어 공사 완료 후 배송일 조율',
    deadline: '2026-10-15',
    completed: false,
  },

  // === 이사/입주 ===
  {
    id: 'moving-1',
    category: 'moving',
    title: '이사업체 예약',
    deadline: '2026-09-15',
    completed: false,
    estimatedCost: 100,
  },
  {
    id: 'moving-2',
    category: 'moving',
    title: '짐 정리 및 포장',
    deadline: '2026-10-15',
    completed: false,
  },
  {
    id: 'moving-3',
    category: 'moving',
    title: '인터넷/TV 이전 신청',
    deadline: '2026-10-10',
    completed: false,
  },
  {
    id: 'moving-4',
    category: 'moving',
    title: '우편물 주소 변경',
    deadline: '2026-10-27',
    completed: false,
  },
];

export const initialExpenses: BudgetExpense[] = [
  { id: 'exp-1', item: '집값', amount: 93000 },
  { id: 'exp-2', item: '취득세', amount: 2790 },
  { id: 'exp-3', item: '부동산 중개수수료', amount: 600 },
  { id: 'exp-4', item: '이사 부대비용', amount: 1500 },
  { id: 'exp-5', item: '이사비', amount: 100 },
  { id: 'exp-6', item: '리모델링(인테리어)', amount: 5000 },
];

export const initialFundSources: FundSource[] = [
  // 주영
  { id: 'fund-1', owner: '주영', source: '일반주식', amount: 6400, lastUpdated: '2026-07-01' },
  { id: 'fund-2', owner: '주영', source: '퇴직연금', amount: 9269, lastUpdated: '2026-07-01' },
  { id: 'fund-3', owner: '주영', source: '현금', amount: 3000, lastUpdated: '2026-07-01' },
  { id: 'fund-4', owner: '주영', source: '청약통장', amount: 700, lastUpdated: '2026-07-01' },
  { id: 'fund-5', owner: '주영', source: '신용대출', amount: 2400, lastUpdated: '2026-07-01' },
  { id: 'fund-6', owner: '주영', source: '가계약금 (납부완료)', amount: 4000, lastUpdated: '2026-07-04' },
  { id: 'fund-7', owner: '주영', source: '주담대', amount: 59150, lastUpdated: '2026-07-01' },
  { id: 'fund-8', owner: '주영', source: '회사 대출', amount: 5000, lastUpdated: '2026-07-01' },
  { id: 'fund-9', owner: '주영', source: '부모님 대출', amount: 5000, lastUpdated: '2026-07-01' },
  { id: 'fund-10', owner: '주영', source: '기타', amount: 1000, lastUpdated: '2026-07-01' },
  // 예원
  { id: 'fund-11', owner: '예원', source: '일반주식', amount: 7300, lastUpdated: '2026-07-01' },
  { id: 'fund-12', owner: '예원', source: '퇴직연금', amount: 920, lastUpdated: '2026-07-01' },
  { id: 'fund-13', owner: '예원', source: '청약통장', amount: 700, lastUpdated: '2026-07-01' },
  { id: 'fund-14', owner: '예원', source: '대출', amount: -900, lastUpdated: '2026-07-01' },
];

// 갤러리 이미지는 이제 Supabase Storage + DB에서 관리
// 초기 데이터는 supabase-setup.sql에서 직접 insert하거나 앱에서 업로드
export const initialGalleryImages: GalleryImage[] = [];
